spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: jangws1003@budit.ai  # ??? Gmail ??
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
